[package]
name = "grades-rs"
version = "0.1.0"
authors = ["Tobias Kerst <tobias.kerst@tobscore.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
