[package]
name = "grades-rs"
version = "0.1.0"
authors = ["Tobias Kerst <tobias.kerst@tobscore.com>"]
edition = "2018"

[lib]
name = "grades"
path = "src/lib.rs"

[[bin]]
name = "grades-bin"
path = "src/bin.rs"