[package]
name = "grades-rs"
version = "0.1.0"
authors = ["Tobias Kerst <tobias.kerst@tobscore.com>"]
edition = "2018"
license = "MIT"

[lib]
name = "grades"
path = "src/lib.rs"

[[bin]]
name = "grade-avg"
path = "src/bin.rs"